### ISSUE TITLE
Exercise 7.49 (b) [proposed by dxiao6]

### ISSUE THREAD

**Issue by Mooophy** [ReadingLab/Discussion-for-Cpp#1]
From [豆瓣讨论](http://www.douban.com/group/topic/74293138/)

dxiao6:
虽然再github上说得很明白了,但还是不理解 为什么加了const就能通过编译了.因为临时变量不能被绑定到普通引用上? 那为什么可以绑定到常量引用上呢?

**Comment by Mooophy** [comment]
目前的答案里貌似有误，回头我和 @pezy 确认一下。

你所谓的【普通引用】其实是【非const的左值引用】，而该临时对象是【右值】。C++禁止把非const的左值引用直接bind到右值上。说白了，C++禁止程序员通过该方式获取临时对象的修改权限。这个权限一旦放开，会导致大量bug，很难调试。

理论上，C++生成的汇编代码里可以获得该权限。换句话说，这是C++作为一门高抽象语言（相对于汇编），为了提高开发效率而做得硬性规定。该规定的意义仅存在于编译过程中，进入run time 之后，该规定就没意义了。

对于右值而言（比如本题里的临时对象），有两种方法进行引用分别为`const&` 和`&&`,也就是只读的左值引用和右值引用。前者用`const`确保了只读，后者用移动语义提供move operation。

最后，如果刚看到ch7的话，建议记住就好了，日后看到右值引用、移动语义再辅以一定代码量，就好理解了。

**Comment by Mooophy** [comment]
拓展阅读：
[How come a non-const reference cannot bind to a temporary object? from SO](http://stackoverflow.com/questions/1565600/how-come-a-non-const-reference-cannot-bind-to-a-temporary-object)

**Comment by pezy** [comment]
> 目前的答案里貌似有误

这块能否再详细说说~
