### ISSUE TITLE
What did you use to OS?   What did you use to compile duration?

### ISSUE THREAD

**Issue by naometh** [ReadingLab/Discussion-for-Cpp#10]
i os : windows7,    Compile : visual 2012.    what you use to?

**Comment by pezy** [comment]
Work: 
- OS: Windows 8.1
- Compile: Visual Studio 2010 + 2013

Home:
- OS: Mac OS + Fedora (Linux)
- Compile: Clang 3.6 + Gcc 4.9
- IDE or Editor: VIM + XCode

**Comment by Mooophy** [comment]
Winodws:
 * Windows 8.1 + vs2013
 * Windows 8.1 + gcc 4.9

Linux:
 * Ubuntu 14.04 LTS + gcc 4.8
 * Ubuntu 14.04 LTS + clang 3.5

**Comment by PeteHenry** [comment]
Sublime text 3 + WinGW 轻量级（这两天刚配）

**Comment by pezy** [comment]
> Sublime text 3 + WinGW 轻量级（这两天刚配）

是 MinGW 吧？:frowning:

**Comment by PeteHenry** [comment]
@pezy 是的，打错字，呵（W与M总是分不清）

**Comment by mudongliang** [comment]
Lab (only Linux):
- Debian Jessie 
- GCC 4.9 + Clang 3.5
- Vim
