### ISSUE TITLE
Maybe some bugs in ex10_32.cpp

### ISSUE THREAD

**Issue by Ocxs** [ReadingLab/Discussion-for-Cpp#12]
@pezy @Mooophy 

```cpp
int main()
{
    std::istream_iterator<Sales_item> in_iter(std::cin), in_eof;
    std::vector<Sales_item> vec;
    
    while (in_iter != in_eof)               //未执行，直接跳过
        vec.push_back(*in_iter++);
    sort(vec.begin(), vec.end(), compareIsbn);    //crash
    for (auto beg = vec.cbegin(), end = beg; beg != vec.cend(); beg = end) {
        end = find_if(beg, vec.cend(), [beg](const Sales_item &item){return item.isbn() != beg->isbn();});
        std::cout << std::accumulate(beg, end, Sales_item(beg->isbn())) << std::endl;
    }
}
```
将
```cpp
    std::vector<Sales_item> vec;
    while (in_iter != in_eof)               //未执行，直接跳过
        vec.push_back(*in_iter++);
```
改成
```cpp
std::vector<Sales_item> vec(in_iter,in_eof);
```

可以修复第一个bug，至于第二个bug，执行到`sort`崩溃，不知道如何修复，按说不应该崩溃才是。

**Comment by pezy** [comment]
sorry, 没看懂你的意思。

我又试着跑了一下这道题的[现存代码](https://github.com/pezy/CppPrimer/blob/master/ch10/ex10_32.cpp)，没有发现 crash 呀？

能说明一下 bug 出现的 case 是什么样的吗？

**Comment by Ocxs** [comment]
上传不了截图，我输入的
```cpp
a 1 1
b 2 2
c 3 3
a 1 1
b 2 2
```

**Comment by pezy** [comment]
还是不懂，我按你的输入，没啥问题啊（在 Windows 上）

![image](https://cloud.githubusercontent.com/assets/1147451/7310357/1985c96e-ea5d-11e4-8250-0d7016c6ade2.png)

**Comment by pezy** [comment]
@Ocxs  :dizzy_face: 按你的输入依然不会 crash 啊。不解。。。

但是我的确发现一个 bug: `compareIsbn` 竟然不是一个比较大小的函数，而是一个判断是否相等的函数。这就导致了按照你的输入，会出现两个 b。我马上修补一下。

**Comment by Ocxs** [comment]
@pezy 终于上传成功了，我输入的就是我之前说的那组数据，就会出现如下结果，将compare函数改一下不会出现如下结果。

![qq photo20150423224819](https://cloud.githubusercontent.com/assets/11175797/7310814/2d1a80d4-ea65-11e4-8eff-8a8141ff3a92.jpg)

**Comment by pezy** [comment]
@Ocxs 嗯，看来 VS 更智能的发现了这个隐蔽的问题。现在没啥问题了吧？

**Comment by Ocxs** [comment]
@pezy 没啥问题了，thx！:smile:
