### ISSUE TITLE
vs2012 x86 本机工具命令提示 cl xx.cpp , 显示“无法打开文件“LIBCMT.lib””...

### ISSUE THREAD

**Issue by PeteHenry** [ReadingLab/Discussion-for-Cpp#15]
由于一直没用过 Git（分布式版本控制），这两天学习了下并在本地配置好，也把 Cpp-Primer clone 到了本地仓库。
看到的一个文件夹中有 N 多 cpp，而且每个都有 main 函数，应该不是在 vs2013 中 1 个 cpp 建 1 个解决方案那么繁琐，google 了下，可以直接用 ```vs2012 x86 本机工具命令提示.exe``` 来调试，出现了 cl 不是内部命令，加下环境变量解决问题了，后来又出现了 ```无法打开文件“LIBCMT.lib” 的问题```，目前还没解决，求肋下。

**Comment by PeteHenry** [comment]
如图：
![test](https://cloud.githubusercontent.com/assets/7722771/7340035/735d9ac4-ecb6-11e4-8e70-416bf7548cc9.PNG)

**Comment by PeteHenry** [comment]
贴一个下 path :
```%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\VSShell\Common7\IDE\;C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\nodejs\;C:\Program Files\MongoDB 2.6 Standard\bin\;C:\Program Files (x86)\LLVM\bin;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;D:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\;D:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\lib\```

**Comment by PeteHenry** [comment]
感觉加下环境变量就可以了（google 的结果大多是这样），是不是环境变量冲突

**Comment by pezy** [comment]
首先，在开始菜单( Win7 )或 Apps( Win8 )中找到 `Visual Studio Tools`:

![image](https://cloud.githubusercontent.com/assets/1147451/7340091/13cbd542-ecb8-11e4-9145-225d7fbb3bcc.png)

然后在里面选择 32 位或 64 位环境：

![image](https://cloud.githubusercontent.com/assets/1147451/7340093/2336d266-ecb8-11e4-99ed-16fca9c4cbb2.png)

然后 `cd` 到相应目录下，用 `cl /EHsc` 来编译相关习题的答案，用 `ex**.exe` 来直接运行编译好的程序，如图所示：

![image](https://cloud.githubusercontent.com/assets/1147451/7340123/9aeabd4a-ecb8-11e4-8eae-aac4e09716f0.png)

-----

Windows 的环境变量是一个非常非常糟糕的设计，杂乱无章，各种冲突，引发莫名其妙的问题。建议不要去修改系统环境变量，而是用 VS 官方提供的环境命令行窗口来进行命令行编译。

**Comment by PeteHenry** [comment]
我用的就是你的操作，先找到 `vs tools` （只有2012）再 cd 到要执行的目录，用 cl 执行，出现的上述无法打开 xx.lib
![default](https://cloud.githubusercontent.com/assets/7722771/7340243/588af692-ecbb-11e4-96ae-9b1c80f42f18.PNG)

**Comment by pezy** [comment]
~~@PeteHenry 请您试试用 x64 的工具编译一下~~

**Comment by pezy** [comment]
@PeteHenry 我注意到一个很严重的问题：

从你贴的 path 里可以看到你用的应该是 `120`，即 VS 2013，为什么又去找 VS2012 的 tools ? 这必须找不到呀？

**Comment by PeteHenry** [comment]
@pezy 64位，还是一样的问题
为什么又去找 VS2012 的 tools ?
我用 `Everything` 查询了下 `Visual Studio Tools` 只有一个，就上面我贴的图

**Comment by pezy** [comment]
> 我用 Everything 查询了下 Visual Studio Tools 只有一个，就上面我贴的图

那请问，您到底安装的是 VS 2013 还是 VS 2012 呢？

**Comment by PeteHenry** [comment]
用的是 `http://msdn.itellyou.cn/` 的 vs2013。
![default](https://cloud.githubusercontent.com/assets/7722771/7340367/b4f538ae-ecbe-11e4-92f5-245a5a3b9220.PNG)
但 vs tools 只有 2012 这, 让我也很尴尬

**Comment by pezy** [comment]
@PeteHenry 好，那就明确了，用 VS 2012 的 tools 肯定是错误的。必须找到 VS2013 的 tools。

再问你，开始菜单里，能否找到 `Visual Studio 2013` 的快捷方式？或者说，你是通过什么打开 VS2013 的？

**Comment by PeteHenry** [comment]
@pezy 谢谢，果然找到个新的，也可以编译，果真太菜，2013 | 2012 傻傻分不清楚
![1](https://cloud.githubusercontent.com/assets/7722771/7340424/fdf41704-ecbf-11e4-8cff-1e85724fa1fa.PNG)
编译出 exe 文件了（想问下，直接执行 exe 后能执行，能在执行后自动删除 exe 文件么？）
还有个问题，前辈平时在 win 平台，直接用 vs 开发，还是随便在哪写用 cl 编译？

**Comment by Mooophy** [comment]
@PeteHenry 如果C++ 和git都新手的话，建议不要在windows平台上玩。因为Vs对新手并不是很有用，又太大。git for windows 也比较麻烦。

试试看 ubuntu + qt creator + gcc。
linux下的 git 也好用得多。

**Comment by pezy** [comment]
@PeteHenry 自动删除这种属于定制化了，可以自己写个简单的批处理脚本执行。

我在 win 上都直接用 VS 开发，有 VS 这么好用的 IDE 还用其他的编辑器写代码纯属蛋疼。当然考虑到 Linux 以及 Mac 下的用户，我没有用 VS 的解决方案去梳理代码。

同意  @Mooophy  的建议，如果是新手，最好还是在 Linux 环境上玩 C++，有了几万代码量之后，再切到 VS 下才会有更深的体验。

**Comment by Mooophy** [comment]
对呀。。我差不多十万行才切windows+vs的。。

**Comment by PeteHenry** [comment]
@Mooophy  @pezy 谢谢前辈们的建议
想过用 ubuntu + gcc ，主要是破电脑装虚拟会卡，平时又要在 win 平台工作（双系统都难），目前无事学习下 c++ （有个问题 js 很烦, c++ 处理很方便） 
感觉 git 是不错，但，我们这破公司都不用版本控制的，所以都没接触过，这两天 Git Bash 的命令差不多都记得和使用过了，再次感谢下前辈，学习的平坦很多
@Mooophy 谢谢 @pezy 辛苦

**Comment by Mooophy** [comment]
前辈毛线，我才大四，还没工作呢。
@pezy 是前辈。

**Comment by PeteHenry** [comment]
@Mooophy 在大学都这么厉害
果然在大学贪玩过了，哎，看书去了
