### ISSUE TITLE
Git 出问题了...

### ISSUE THREAD

**Issue by PeteHenry** [ReadingLab/Discussion-for-Cpp#16]
前些天配置了 git ，也 clone 了 Cpp-Primer 到本地仓库，看了下每个文件夹都有 n 个 cpp 文件，每个都有 mian 函数，感觉用 vs2013 来学习，太过了，就配置了个 Sublime Text 3 + MinGw 轻量级环境

![default](https://cloud.githubusercontent.com/assets/7722771/7365660/dbd34004-edc4-11e4-9bd9-8e0532a90ea7.PNG)

配置好了后，发现 git 不能与远程仓库交互了出现的下面的问题：

![default](https://cloud.githubusercontent.com/assets/7722771/7365716/73244cd2-edc5-11e4-9744-2072ae2239f2.PNG)

google 后，说可能是 22 端口封了，换个就行，但换成 443 或 4443 都没成功，来请教下

@pezy  @Mooophy  谢谢

**Comment by pezy** [comment]
翻墙，或改用[ `https` 方式](https://help.github.com/articles/which-remote-url-should-i-use/#cloning-with-https-recommended)连接。

换成 443 是不得已的办法，请参考[这个步骤](https://help.github.com/articles/using-ssh-over-the-https-port/)。

**Comment by PeteHenry** [comment]
已过墙
应该不是墙的问题， `https` 方式也不能交互（随便 clone 下），如图：
![default](https://cloud.githubusercontent.com/assets/7722771/7366113/82fe75bc-edc8-11e4-839e-e63e463940bb.PNG)
下班了，吃完饭我再 google 下，明天才能来改

谢谢

**Comment by PeteHenry** [comment]
telent 127.0.0.1 1433 可以
telent 127.0.0.1 22 不行
telent 127.0.0.1 433 也不行
端口问题？系统是 Win8.1
可是无论我在出入站规则中增加22和433后，也不能 telnet 了了，关闭防火墙也不能 telent
同时 Git 不能与远程交互，不懂了

**Comment by PeteHenry** [comment]
安装 cygwin 后，Git 还是用不了，果然被玩坏了，帖图
![1](https://cloud.githubusercontent.com/assets/7722771/7466569/2343782a-f318-11e4-9deb-318b551f081a.PNG)
![2](https://cloud.githubusercontent.com/assets/7722771/7466571/29a79840-f318-11e4-94be-8d2d84e8a1d6.PNG)
![3](https://cloud.githubusercontent.com/assets/7722771/7466573/2e2b90a6-f318-11e4-977e-24057b550add.PNG)
感觉，电脑环境完全错乱了

**Comment by PeteHenry** [comment]
ok，解决了，代理劫持的问题
![default](https://cloud.githubusercontent.com/assets/7722771/7466830/7e9d029a-f31d-11e4-9929-3c9ef37a18b2.PNG)

**Comment by pezy** [comment]
@PeteHenry  恭喜！ :beers:
