### ISSUE TITLE
Exercise 7.35 问题

### ISSUE THREAD

**Issue by csbdong** [ReadingLab/Discussion-for-Cpp#17]
Exercise 7.35
Explain the following code, indicating which definition of Type or initVal is used for each use of those names. Say how you would fix any errors.

``` C++
typedef string Type;
typedef string Type;
Type initVal();
class Exercise {
public:
    typedef double Type;
    Type setVal(Type);
    Type initVal();
private:
    int val;
};
Type Exercise::setVal(Type parm) {
    val = parm + initVal();
    return val;
}
```

有个疑问，为什么`Type Exercise::setVal(Type parm)` 中第一个Type是指`typedef string Type`
按照查找的原则不是先在成员函数内查找（此处未找到），然后在类内查找吗？（此处找到）

**Comment by Ocxs** [comment]
在@pezy 回答之前先说一下自己的理解,讲错了求指教！  
其实这句代码是有错的

``` cpp
Type Exercise::setVal(Type parm) {
    val = parm + initVal();
    return val;
}
```

错误的原因是重载出错（vs2013给的报错解释，它将其理解成重载函数，但是重载函数不能只有返回类型不同，而其他一样 . ）
至于为什么出错，我的理解是：`Type Exercise::setVal(Type parm)`定义在类外面，而恰好类外面也有`Type`的声明，而类中的那个`Type`跟`Type Exercise::setVal(Type parm)`不在同一个作用域(相对比来说，可以理解typedef double Type;是在局部作用域，`Type Exercise::setVal(Type parm)`在全局作用域，其实这样是不对的），所以函数就优先使用类外面的`Type`，也就是使用了`typedef string Type;`，但是使用这个的后果就是造成重载出错。

至于你说的那个规则

> 按照查找的原则不是先在成员函数内查找（此处未找到），然后在类内查找吗？（此处找到）

如果我没理解错的话，可能就是你理解的地方有点小偏差。这里的第一个`Type`是返回类型，返回类型必须是在使用前确保可见。不会像你说的那样，没找到的情况下继续在类的作用域里寻找。（中文版P254有讲）

**Comment by Ocxs** [comment]
@Mooophy  在顺便歪个楼，（@csbdong 非常不好意思，待会知道答案后我会删除这层楼的），我看您star了AdaBoost  这个项目，特别想问一下，你是不是也用过svm来训练数据啊？（现在有这方面问题，百思不得其解 啊）

**Comment by Mooophy** [comment]
@Ocxs 
我也是刚刚接触，完全一头雾水 :sob:

**Comment by Ocxs** [comment]
@Mooophy 好吧，我用libsvm训练一组数据，然后在用libsvm预测的时候识别率虽然不高，好歹平均也有70%的识别率，但是转opencv下面训练的时候，实时检测，总是只能识别出一种结果，不知道为啥？ :sob:

**Comment by Mooophy** [comment]
@Ocxs 
你好歹还训练过。。我根本没训练过。。

**Comment by Ocxs** [comment]
@Mooophy 唉，好吧，看来我还要在研究研究哪出问题了，你也是用opencv的吗？

**Comment by Mooophy** [comment]
@Ocxs 也用。。水准很烂，基本就不太会。刚开始看adaboost的论文。。回头问问你训练数据的流程。。

**Comment by Ocxs** [comment]
@Mooophy 好吧，我水准也很烂，我怕误导你了，我把这些都删了，省的把楼主的原问题给歪了！

**Comment by Mooophy** [comment]
@Ocxs 嗯嗯

**Comment by Mooophy** [comment]
我的看法是这样：

``` cpp
typedef string Type;
Type initVal();
class Exercise {
public:
    typedef double Type;//此处发生 name hiding，hide了全局的Type。
    Type setVal(Type);
    Type initVal();
private:
    int val;
};

Type Exercise::setVal(Type parm) {
//返回值类型是 string，因为前置的返回值类型不属于class body之内，所以全局Type可见, 而Exercise::Type不可见。
    val = parm + initVal();
    return val;
}
```

本章节课文的例子和这个基本一样，建议仔细阅读。 @csbdong

**Comment by Mooophy** [comment]
这个代码我试了三个编译器，vs2013的报错是无法重载。而g++ 和 clang的报错一致，都是函数的声明和定义不匹配。C++不允许class体外的成员函数声明，故可知此处vs2013是出bug了。

应该是前端分析的智能算法什么地方出错了，没理由识别成重载。

以下是三个编译器的报错。
vs2013:

``` haskell
Source.cpp(16) : error C2556: 'Type Exercise::setVal(Exercise::Type)' : overloaded function differs only by return type from 'Exercise::Type Exercise::setVal(Exercise::Type)'
        Source.cpp(11) : see declaration of 'Exercise::setVal'
Source.cpp(16) : error C2371: 'Exercise::setVal' : redefinition; different basic types
        Source.cpp(11) : see declaration of 'Exercise::setVal'
```

g++ 4.8

``` haskell
error: prototype for 'Type Exercise::setVal(Exercise::Type)' does not match any in class 'Exercise'
 Type Exercise::setVal(Type parm) {
      ^
candidate is: Exercise::Type Exercise::setVal(Exercise::Type)
     Type setVal(Type);
          ^
```

clang 3.4

``` haskell
error: return type of out-of-line definition of 'Exercise::setVal' differs from that in the declaration
Type Exercise::setVal(Type parm) {
省略若干
```

**Comment by csbdong** [comment]
@Mooophy 

``` C++
Type Exercise::setVal(Type parm) {
    val = parm + initVal();
    return val;
}
```

那么此例中，是不是返回值Type类型和形参的类型Type都是指代的外围的

``` C++
 typedef string Type
```

??
我看编译下来的结果好像形参类型却是类内定义的Type，即Exercise::Type???

> //返回值类型是 string，因为前置的返回值类型不属于class body之内，所以全局Type可见, 而Exercise::Type不可见。

**Comment by Mooophy** [comment]
``` cpp
Type Exercise::setVal(Type parm) {
//class之外--->|<------------ class 之内
    val = parm + initVal();
    return val;
}
```

所以 该方法的参数是`Exercise::Type`即`double`

**Comment by csbdong** [comment]
@Mooophy  不太明白，是说前置的返回类型是class body之外的，其余部分属于类内吗？？？

**Comment by Mooophy** [comment]
是的

**Comment by csbdong** [comment]
好吧，看来还得仔细点，thx

**Comment by csbdong** [comment]
@Mooophy  
@Ocxs 给我的解释中提到：
中文版P254上面这样说：声明中使用的名字，包括返回类型或者参数列表中使用的名字都必须在使用前保证可见。
英文版**Name Lookup for Class Member Declarations**部分。
那么为什么**前置的返回类型是class body之外的，其余部分属于类内**呢？？
按照@Ocxs的解释返回类型与形参列表的处理不应该等同吗？ 是解释出错了还是我理解错误了？
书上有没有相关的解释呢？

**Comment by Mooophy** [comment]
@Ocxs 的解释我没太看懂。但这里跟重载没关系，vs很可能是出了个小bug。

我手里没有中文版，谁提供一下对应的英文版章节号。

最重要的是，下面这两句话不矛盾：

```
1.声明中使用的名字，包括返回类型或者参数列表中使用的名字都必须在使用前保证可见。
```

```
2.前置的返回类型是class body之外。
```

**Comment by Mooophy** [comment]
仔细理解一下：这两句话的含义和差别。

`保证可见` **包括但不限于** `在class内声明过`，还可以是POD，就是`int`,`long`之类的内建类型，以及外部声明过的类型比如include进来的，比如`std::string`,`std::vector<int>`。只要相应的header被include进来了，那就`可见`了啊。

**Comment by csbdong** [comment]
@Mooophy   对应的英文版，是7.4.1节 **7.4.1. Name Lookup and Class Scope** 第一部分 **Name Lookup for Class Member Declarations**

**Comment by csbdong** [comment]
@Mooophy  我之前的疑惑是不明白为什么返回类型是类体之外，而形参列表却在之内，现在在书上找到答案了：
英文版：7.4节**7.4. Class Scope** 第一小节**Scope and Members Defined outside the Class** 中提到：
一旦遇到类名，定义的剩余部分就在类的作用于之内了，这里的**剩余部分包括参数列表和函数体。**

明白了。

**Comment by csbdong** [comment]
还是看书不仔细。 THX ALL。

**Comment by Mooophy** [comment]
这种情况下，`前置返回值类型`就是class之外的，这也是C++11加入了`后置返回值`的原因。这也是我措辞`前置返回值类型`，而没说`返回值类型`的原因。因为`后置返回值类型`是class之内的。试一下这两段代码：
前置返回值

``` cpp
struct Foo
{
    using T = int;
    T bar(int, long );
};

T Foo::bar(int i, long j) 
{
    return 42;
}

int main()
{

}
```

后置返回值

``` cpp
struct Foo
{
    using T = int;
    T bar(int, long );
};

auto Foo::bar(int i, long j) -> T 
{
    return 42;
}

int main()
{

}
```

**Comment by Mooophy** [comment]
前者无法编译，后者正常编译。
以后多写template就熟悉了。

**Comment by csbdong** [comment]
3Q
