### ISSUE TITLE
关于左值和右值的讨论

### ISSUE THREAD

**Issue by mudongliang** [ReadingLab/Discussion-for-Cpp#18]
今天看了第四章的左值和右值，感觉不是很理解，大家能不能给点意见和说明？
@pezy @Mooophy

**Comment by Mooophy** [comment]
第四章出现的左值右值不必深究，后文会有大篇幅讨论和习题。

**Comment by pezy** [comment]
@mudongliang 这种讨论，希望你先给出自己的理解。否则题目太大，讨论起来简直无边无际。

另，同意 @Mooophy ，建议先放下疑惑；如果实在想瘙痒，请参考：[这里](../blob/master/Reference.md#expression)

**Comment by Mooophy** [comment]
C++这种东西，复杂、庞杂、驳杂。哪个部分先深入、哪个部分后深入，是非常重要的策略。这个策略问题，非常影响学习效率，也影响C++学习对CS整体知识的理解。

同时，我的建议是负责任的，是站在你的角度考虑过的。这一点也是你尤其缺乏的。 @mudongliang

**Comment by ioshine** [comment]
我很水刚开始学，晕晕乎乎，我的理解是左值能在等号左侧，能往里写东西，右值能在等号右侧的，能读东西。。。
