### ISSUE TITLE
类内初始值和构造函数的初始值

### ISSUE THREAD

**Issue by csbdong** [ReadingLab/Discussion-for-Cpp#20]
``` C++
class Test
{
    public:
    Test()=default;
    Test(int i,string j):a(i),b(j);
    private:
    int a=0;
    string b;
}
```

现在我调用第二个构造函数实现一个Test类的对象t，如下：

``` C++
Test t(6,"aaa");
```

那么，现在有一个问题。
在书上的7.4.1节名字查找提到了类内部的解析方法：先编译所有成员的声明，然后是函数体。
在7.5节构造函数再探一节中讲到了构造函数初始值是对成员直接初始化。。。
在这个例子中：成员a与成员b分别被构造函数**初始化**成6与aaa。为什么不是在编译阶段a与b分别初始化成了0与空串，然后再被分别**赋值**了？

**Comment by pezy** [comment]
`int a = 0;` 会被忽略，`a` 会直接取 6， `b` 同理。

> If a non-static data member has an in-class brace-or-equal initializer and also appears in a member initializer list, then member initializer list is executed and brace-or-equal initializer is ignored:
> 
> ``` cpp
> struct S {
>     int n = 42;
>     S() : n(7) {} // will set n to 7, not 42
> };
> ```

更多相关标准规则请参考：http://en.cppreference.com/w/cpp/language/initializer_list
