### ISSUE TITLE
关于typedef的问题

### ISSUE THREAD

**Issue by Ocxs** [ReadingLab/Discussion-for-Cpp#27]
刚刚写代码遇到一个奇怪的问题，环境：win7 + code::block ,代码如下：

``` cpp
struct m_num
{
    int num;
    bool flag = true;
};
int main()
{
    int N = 0, K = 0;
    cin >> N >> K;
    typedef m_num arrT[K];
    arrT data[N];
    return 0;
}
```

这样的代码没有报错，为什么呢？数组的大小不是要预编译的时候就要确定好吗？
而且如果我把那几行代码放入全局中，就会报错，

``` cpp
struct m_num
{
    int num;
    bool flag = true;
};
int N = 0, K = 0;
cin >> N >> K;
typedef m_num arrT[K];
arrT data[N];
int main()
{
    return 0;
}
```

---

``` cpp
报错内容：
error: array bound is not an integer constant before ']' token
error: 'arrT' does not name a type
```

这是为什么呢？@pezy @Mooophy

**Comment by pezy** [comment]
这你应该问 Code::Block 是怎么回事，它用的什么编译器。

`typedef m_num arrT[K];` 显然是不符合 C++ 标准的。也许符合 C99（我并未严格查证，只是有印象）。

验证这个也很简单，去找 GCC 最新版本或 Clang 最新版本，编译一下便可知。我用 Clang 试了，直接报错。

**Comment by Ocxs** [comment]
@pezy 3q ！ 他的编译器是gcc，版本未知，可能就是编译器的问题了，**能不能推荐了轻量级的IDE？**带点智能提示，不需要特别强大，最近在做数据结构的题目，用vs太麻烦，dev-c++没有智能提示，而且编译器也是gcc，对c++支持的不是特别好，有的函数vs下能用，到这就不行了！

**Comment by pezy** [comment]
[CLion](https://www.jetbrains.com/clion/)

任何人免费用三十天，学生注册之后，可以用一年。

**Comment by Ocxs** [comment]
@pezy  3q！:smile: 继续刷题！

**Comment by pezy** [comment]
@Ocxs 补充一个：[Qt Creator](http://www.qt.io/download-open-source/), 轻量，对标准支持的好。

**Comment by Ocxs** [comment]
@pezy 好的，我在下载一个它看看！谢谢！

**Comment by Ocxs** [comment]
@pezy 出问题了，我下载的是[这个](http://www.qt.io/download-open-source/#section-2),没有用那个installer，下载的是Qt Creator 3.4.1 for Windows (71 MB)    (info)

这个下载的对吗？我下载下来之后好像用的不对头啊

**Comment by pezy** [comment]
@Ocxs 对，就是这个，哪里不对头？

**Comment by Ocxs** [comment]
@pezy 不用麻烦啦，我刚刚把code::blocks的编译器换成vs2013的，刚好二者的优点结合到一块去，可以不错的使用了 :smile:

**Comment by Ocxs** [comment]
hello world 都过不了啊，不知道是不是我使用的不对。

![image](https://cloud.githubusercontent.com/assets/11175797/8063335/b41b6326-0f06-11e5-8a72-478e7d71977e.png)

我是直接打开一个cpp文件的

**Comment by Ocxs** [comment]
新建项目工程也是不行
![image](https://cloud.githubusercontent.com/assets/11175797/8063427/310260b0-0f07-11e5-9612-d2914336dd36.png)

![image](https://cloud.githubusercontent.com/assets/11175797/8063414/1ca88766-0f07-11e5-9eaa-53a6716d6756.png)

**Comment by pezy** [comment]
@Ocxs  请选择**非Qt项目**中的纯 C++ 项目。

**Comment by Ocxs** [comment]
@pezy  还是不行，还是出现上面那种情况，NO valid kits found，不知道是怎么回事
