### ISSUE TITLE
如何理解「一个指针指向某对象，同时另一个指针指向另外对象的下一地址，此时也有可能出现这两个指针值相同的情况，即指针相等。」？

### ISSUE THREAD

**Issue by acgtyrant** [ReadingLab/Discussion-for-Cpp#29]
参见《C++ Primer 中文版（第五版）》第 50 页和原版第 55 页。

**Comment by pezy** [comment]
书不在身边，可以说一下这句话的章节号和小节号吗？或者有英文原文更好。

**Comment by acgtyrant** [comment]
原版章节是 2.3.2 Pointer, 小节是 Other Pointer Operations, 原文是：

> Note that it is possible for a pointer to an object and a pointer one past the end of a different object to hold the same address. Such pointers will compare equal.

**Comment by pezy** [comment]
@acgtyrant 

我说一下我的理解吧，**内存一块连续的分布，指针因为过于自由，可能会指到不属于它的地方**。

啥意思呢？譬如一个我们有两个对象，一个数组对象: `int obj[4] = {0, 1, 2, 3};`，另一个字符串对象: `char other_obj[] = "xxooxxoo";`。它们俩在内存里有可能是这样的：

```
<---otherObj--->    <--obj-->
+-+-+-+-+-+-+-+-+---+-+-+-+-+
|x|x|o|o|x|x|o|o|...|0|1|2|3|
+-+-+-+-+-+-+-+-+---+-+-+-+-+
                     ^
                     a pointer one past the end of other obj
```

然后我理解的 `a pointer one past the end of a different object` 就是上图所示的指针所指的地方。显然，那里是一个 UB( 未定义的行为 )，但因为内存通常是连续分配的，有可能后面就是接着 `obj` 这个对象的。

我花了点时间，找了一个 GCC 4.9 上可以复现该现象的例子，你可以跑一下，参考参考：

``` cpp
#include <iostream>
#include <cassert>

int main()
{
    int obj[4] = {0, 1, 2, 3};
    char other_obj[] = "xxooxxoo";

    void* pObj = static_cast<void*>(obj);
    void* pOtherObj = static_cast<void*>(other_obj + 16);

    std::cout << pObj << std::endl;
    std::cout << pOtherObj << std::endl;

    assert(pObj == pOtherObj);
}
```

可以看到 `other_obj + 16` 是一个明显越界的指针(a pointer one past the end of other object)，但凑巧的是，它恰好与指向 `obj` 对象的指针相等。

**Comment by acgtyrant** [comment]
也就是说「另一个指针指向另外对象的下一地址」本身就已经不合法了啊……

**Comment by pezy** [comment]
@acgtyrant 

是的，但是编译运行完全没错......

C++ 一是为了兼容 C，二是为了效率，留了很多可供 hack 的行为，这就是一种。虽然是 UB，但是在固定编译器下特定情况下，可以保证程序的高效运转。但由于现在 C++ 编译器越来越牛，底层优化已经做到惊世骇俗，这样的行为就毫无意义了。

甚至可以看到 C++ primer 是完全避免使用裸指针的，更加推荐使用引用。

**Comment by Mooophy** [comment]
@acgtyrant 
CP5精华在于初窥C++全貌，而非细节的深入探讨。这句话的意义在于使全段内容的逻辑完整，而非知识性的介绍。不建议在CP5的阅读中过多纠结。

不知你功底如何，如果对这类知识感兴趣，建议从计算机组成原理、汇编语言或编译的角度入手。这种问题在C++里是搞不清楚的, 即使把CP5读十遍也是徒劳。

缀一句，C++的学习中一定要分清主次，建议以STL,OO，Template，functional为主，相关知识多下功夫。其他知识点有个印象就行，不要深究。

**Comment by acgtyrant** [comment]
@Mooophy 我读过 CSAPP, 有比较不错的Ｃ基础。

你这么一说，可以请你针对 STL, OO, TMP, functional 四大主题对 CP5 目录分个类吗？我目前学到了 3.3 标准库类型 vector; 打算跳过第四章表达式，第五章语句不读了；不知第十二章动态内存是属于什么内容；第 IV 部分高级主题大概也不是重点。

**Comment by pezy** [comment]
@acgtyrant 

STL: ch3, 9, 10, 11.
OO:  ch7, 13, 14, 15.
TMP: ch16
functional 和 lambda 表达式：从 ch10 开始引入，贯穿始终。

ch12 属于 C++ 的内存管理范畴 （对应 C 里面的 malloc, memset, memcpy, memmove 的内容），具体说，就是涉及几种智能指针的用法，和 allocator 类。

> 第 IV 部分高级主题大概也不是重点。

Agree.

**Comment by Mooophy** [comment]
对 就 @pezy 列这些，ch3不用看了，直接 ch7 + ch9-ch16。
