### ISSUE TITLE
指向常量的常量指针 是否与 指向常量的引用 类似

### ISSUE THREAD

**Issue by PeteHenry** [ReadingLab/Discussion-for-Cpp#3]
```cpp
const int ival = 1024; 
const int *const pi = &ival; 
```
指向常量的常量指针=指针中存放地址的值和所指对象，都不能改变。 
即 pi 一直指向 ival，同时ival 对象的值是不能被改变的。 

```cpp
const int ival = 1024; 
const int &ri = ival; 
```
指向常量的引用，所指向的对象不能改变，因为引用是别名所以引用是一直指向原对象。 
即 pi 一直指向 ival，同时ival 对象的值是不能被改变的。 

Q: **两者在某时是一样的？**
 
As a beginner , the problem might be foolish! 
有问题不知道答案，总是感觉有些不舒服。 

谢谢 解答

**Comment by pezy** [comment]
> Q: 两者在某时是一样的？

如果是你例子里举出的情况，我觉得是一样的。

你的 `pi` 很特殊，既是一个 top-level 又是一个 low-level 指针。那么从效果上，的确与 `const` references 别无二致。

但从根本上讲，指针与引用有几个本质区别（无论是否有 `const` 修饰）

- **指针可以指向 `nullptr`**，引用无法绑定到“空”上。[1]
- **引用没有地址**，你对 `ri` 取地址操作，取得的是 `ival` 的地址。但指针有独立地址，对 `pi` 取地址，取得的是 `pi` 自己的地址。
- 指针自己的地址，存放的是其指向对象的地址。即，`pi` 的地址里存放的是 `ival` 的地址。而引用，仅仅是个别名，它就是 `ival` 的另一个名字而已。

-----

涉及代码：

[1]:
```cpp
const int * const pi = nullptr; // 合法
```

**Comment by PeteHenry** [comment]
谢谢 解答
换言之，当指针即是顶层 const 也是底层 const 时，两都类似
当然，只是类似指针和引用的区别还是存在了

**Comment by pezy** [comment]
@PeteHenry 是的。

**Comment by Mooophy** [comment]
@pezy ：
这个repo没必要close issue吧？
感觉保持open便于后来者查询一些。

**Comment by pezy** [comment]
@Mooophy 

是这样的，我希望对问题有一个基本的区分：

- 讨论清楚了的（题主认可）
- 不了了之的（题主还有疑问，但无人可以解答清楚，需要先放着）

前者置于 close 中，后者置于 open 中，目的也同样是为了更好查询。

另外，对于 close 后的问题，查询起来也是一样方便的：

![image](https://cloud.githubusercontent.com/assets/1147451/7223621/443c3d90-e757-11e4-8178-71b229bf0837.png)
![image](https://cloud.githubusercontent.com/assets/1147451/7223615/2bf1b09e-e757-11e4-979d-16e72aff6ff5.png)

-----

为了更有效的查询，我设置了一些标签来区分大致的范围。如 Ptr&Ref 代表指针引用基础知识，*value 代表左值右值表达式语义的知识。

当然我不保证自己能一直维护。。。尽量好了。

**Comment by Mooophy** [comment]
@pezy 嗯，也好。的确是有益的探索，就建议别搞太复杂，否则很难把维护权限交出去。时间一久维护人员的压力会越来越大。

**Comment by pezy** [comment]
@Mooophy :ok_hand: 一切从简。

另外一个问题我在犹豫：**标题**对于查询起来方便尤为重要，上面截图里搜索出来那个，显然就是个反例，应该没人可以通过这个标题得知问题是什么，过一段时间，当事人和解答人可能也觉得不知所云。你觉得这块需要进一步编辑吗？还是不用管它？ :confused:

**Comment by Mooophy** [comment]
@pezy 不用管了吧，能用markdown，能和主repo彼此reference已经是一大进步了。

优化标题搜索是非常困难的：
* 依赖github本身的搜索能力，而github的搜索能力（特别是针对中文）显然普普，日后也难以改善
* 建立严格的标题格式，这又会提高参与者的门槛，增加维护者的工作量。

所以我的意见就是，顺其自然好了。

**Comment by pezy** [comment]
:white_check_mark: Agree.
