### ISSUE TITLE
g++ 用-std=c++11编译不过insert的返回值新特性

### ISSUE THREAD

**Issue by hexinzhe** [ReadingLab/Discussion-for-Cpp#37]
这是代码，目的是测试新标准insert接受元素范围的版本。vs2013可以正常运行
    vector<int> v;
    list<int> lst{1,2};
    auto it = v.insert(v.end(),lst.begin(),lst.end());
g++报的错
error: 'void it' has incomplete type
返回值类型为void

**Comment by pezy** [comment]
是的，至少 Gcc 4.9.2 还没实现这个特性。

请见我很早之前在 StackOverflow 上提的问题：http://stackoverflow.com/questions/29690369/why-gcc-4-9-2-cant-support-stdstring-insertiterator-range-to-return-iterat

**Comment by hexinzhe** [comment]
哦,多谢
