### ISSUE TITLE
关于literal type，literal class

### ISSUE THREAD

**Issue by HypnoS-s** [ReadingLab/Discussion-for-Cpp#43]
```
struct Data{
    int ival;
    string s;
}
```

Data不是一个literal class，因为string类型不是literal type。
对于这个literal type疑问，到底怎么才算是literal type？

http://en.cppreference.com/w/cpp/concept/LiteralType
http://en.cppreference.com/w/cpp/types/is_literal_type

**Comment by HypnoS-s** [comment]
在书P66的Literal Types一节中，有

```
The types we can use in a constexpr are known as "literal types" because they are simple enough to have literal values.
```

和

```
Of the types we have used so far,the arithmetic, reference, and pointer types are literal types.
```

而arithmetic包括integral type和floating-point type。

**Comment by pezy** [comment]
你贴出的链接里已经有定义了：

**Literal types** are the types of [**constexpr variables**](http://en.cppreference.com/w/cpp/language/constexpr) and they can be constructed, manipulated, and returned **from constexpr functions**.
