### ISSUE TITLE
关于ex_7_06答案不应该和书上一致吧

### ISSUE THREAD

**Issue by meilin96** [ReadingLab/Discussion-for-Cpp#46]
题目是"对于函数add、read和print,定义你自己的版本"。
那么答案就不应该是前面书上已经给出的代码了，而且此时还没学到IO库应该写不出答案那样的代码啊？

**Comment by meilin96** [comment]
继续看下面的题发现Person类的读取和打印函数也用到了IO类的引用作为参数和返回值，我是不是该先看第8章的内容orz

**Comment by pezy** [comment]
不太过于教条, 一个 `read` 和 `print` 还不至于就要去看第八章... 而且第八章的重点也并不在这. 这也并不难理解呀.

的确是前面给出的代码, 但那肯定是标准答案不是? :jack_o_lantern:

**Comment by meilin96** [comment]
嗯嗯，感谢回复
