### ISSUE TITLE
float ** 不能转换到const float**？

### ISSUE THREAD

**Issue by Ocxs** [ReadingLab/Discussion-for-Cpp#51]
下午看写代码遇到一个bug，搞了半天才知道`float**`不能直接转换到`const float**`，我在SO上找到类似[提问](http://stackoverflow.com/questions/2463473/why-am-i-getting-an-error-converting-a-float-to-const-float) 。看完之后仍有疑惑，大家仿佛都在强调一点，一旦可以转换，就会导致其丢失const属性？

问题1：对于`const float**`来说，这里的const到底修饰的是什么呢？直面翻译是：a pointer to pointer to const float? 难道`const`修饰的就是的是pointer to pointer to的值？也就是你在[这里](http://segmentfault.com/q/1010000002568358?_ea=359058)提到的，const修饰的是别人，不是自身.

那对于`const float * const *`来说,直面翻译就是：a constant pointer to pointer to a const float？（从左往右看），第一个const修饰的是别人，第二个const修饰的是自身第一个pointer。

不知道上述我的理解，是否对？

问题2：
为啥不能转换？他们说了好多，我还是不太明白为啥？

代码：

``` cpp
    char *c = "cp";
    const char *pc = c; 
    const char** pcc = &pc; //1: not allowed

    std::cout << "*c is " << *c << std::endl;           // *c is c
    std::cout << "*pc is " << *pc << std::endl;     // c
    std::cout << "**pcc is " << **pcc << std::endl;     // c

    char *d = "ds";
    c = d;
        // *c = 'd';       // it will crash   

    std::cout << "*c is " << *c << std::endl;           // d
    std::cout << "*pc is " << *pc << std::endl;     // c
    std::cout << "**pcc is " << **pcc << std::endl;     // c

    int a = 1;
    int *b = &a;
    const int *bb = b;
    const int **bbb = &bb;

    std::cout << "a is " << a << std::endl;         // 1
    std::cout << "*b is " << *b << std::endl;           // 1
    std::cout << "*bb is " << *bb << std::endl;     // 1
    std::cout << "**bbb is " << **bbb << std::endl;     // 1

    a = 2;

    std::cout << "a is " << a << std::endl;         // 2
    std::cout << "*b is " << *b << std::endl;           // 2
    std::cout << "*bb is " << *bb << std::endl;     // 2
    std::cout << "**bbb is " << **bbb << std::endl;     // 2
```

![image](https://cloud.githubusercontent.com/assets/11175797/10867869/71b2e3ae-80b4-11e5-9a5b-613f11942ebc.png)
                                                                    （1）图1

![image](https://cloud.githubusercontent.com/assets/11175797/10867883/db8ceaae-80b4-11e5-8d13-4bacca9250ce.png)
                                                                     （2）图2
代码中可以看到第一个`const char**`没变，第二个`const int**`变了，之所以我第二个举例要换成`const int **`，是因为我在vs2013里写 `*c = 'd';`会崩溃，所以就把`char`换成`int`了，所以我就比较迷糊了。

（顺便提一下，@pezy 你之前在segmentfault上的[回答](http://segmentfault.com/q/1010000002568376)中 `const char *` <==> `const * char`这个应该是有问题的吧， `const * char`应该是错误的，`*`前面应指明类型)

**Comment by pezy** [comment]
@Ocxs 

危险的原因一个例子就很清楚了。

``` cpp
class Foo {
public:
  void modify();  // make some modification to the this object
};
int main()
{
  const Foo x;
  Foo* p;
  const Foo** q = &p;  // q now points to p; this is (fortunately!) an error
  *q = &x;             // p now points to x
  p->modify();         // Ouch: modifies a const Foo!!
  // ...
}
```

请好好理解这个例子。

> 顺便提一下，@pezy 你之前在segmentfault上的回答中 const char \* <==> const \* char这个应该是有问题的吧， const \* char应该是错误的，*前面应指明类型)

对， 笔误了， 已修正， 谢谢。

**Comment by pezy** [comment]
@Ocxs 

补充一下吧。 感觉你考虑的好复杂。

简单理解：
1. `Foo* <=> const Foo* <=> Foo const*` (这个懂吧？我在sf上那个答案就在说这个)
2. `Foo** <=> (Foo*)* <=> (const Foo*)* <=> (const Foo*) const* <=> const Foo* const*` (先把Foo\* 看成一个整体，然后代换 1 里的转换原则)

所以 `Foo**` 对应的是 `const Foo* const*`，而你把其等同于 `const Foo**`， 不是显然丢掉了一个 const 属性么。当然无法划等号。

**Comment by Ocxs** [comment]
@pezy sorry,昨天考试，所以最近准备考试没有来得及回复，第二个例子讲的很形象，之前看那个例子半懂不懂的，你补充的丢失的一个const属性，让我明白了！

``` cpp
class Foo {
public:
  void modify();  // make some modification to the this object
};
int main()
{
  const Foo x;
  Foo* p;
  const Foo** q = &p;  // q now points to p; this is (fortunately!) an error
  *q = &x;             // p now points to x
  p->modify();         // Ouch: modifies a const Foo!!
  // ...
}
```

对于这个例子来说，因为丢失了那个const属性，所以*q才可以改变，指向其他地方，才会有上面`modifies a const Foo!!`，所以为了杜绝这种现象发生，就规定`const Foo** q = &p;`这样是错误的，也就是`float**`不能转换到`const float**`.

多谢多谢！:+1:
