### ISSUE TITLE
运行下面这段数列求和程序，当数列数是偶数是出现循环？？

### ISSUE THREAD

**Issue by naometh** [ReadingLab/Discussion-for-Cpp#53]
使用vector输入一组数，求相邻两个数的和。当输入的数的个数是偶数时，程序运行出现显示5个数为0的死循环。为奇数时正常显示，程序如下：

```
  #include <iostream>
  #include <vector>

  using namespace std;

  int main()
 {
    vector<int> vInt;
    int iVal;
    cout << "Enter a group of numbers: " << endl;
    while(cin >> iVal)
         vInt.push_back(iVal);
    if(vInt.cbegin() == vInt.cend())
    {
        cout << "No any elements" << endl;
        return -1;
    }
    cout << "Sum of each pair of adjacent elements each is: " << endl;
    // Take advantage of auto to deduce the type of it
    for(auto it = vInt.cbegin(); it != vInt.cend() - 1; it++)
    {
        // Sum of each pair of adjacent elements
        cout << (*it + *(++it)) << " ";
        // Each line output 5 numbers
        if((it - vInt.cbegin() + 1) % 10 == 0)
            cout << endl;
    }
    // If the numbers of the elements are odd, process the end of an element single-handed
    if(vInt.size() % 2 != 0)
        cout << *(vInt.cend() - 1);

    return 0;
  }
```

这是什么问题？

**Comment by pezy** [comment]
> for(auto it = vInt.cbegin(); it != vInt.cend() - 1; it++)
>     {
>         // Sum of each pair of adjacent elements
>         cout << (*it + *(++it)) << " ";

问题出在这里， 迭代器会越界，请调试检查。

**Comment by naometh** [comment]
我运行编译器通过，但是一输入为偶数数目的数列，就会出现00000的循环，你说超出了iterator的范围。我是C++新手，不会改啊。谢谢，请你帮忙改下，谢谢。

**Comment by Ocxs** [comment]
change `it != vInt.cend() - 1;` to `it != vInt.cend();`

**Comment by naometh** [comment]
You change it != vInt.cend() - 1; to it != vInt.cend(); the sequence of even can display correctly after compiling. But input the sequence of odd is wrong after compiling, the program always loops.

**Comment by Ocxs** [comment]
我是看你上面说输入偶数，所以给你改的那个，你输入奇数会出问题是因为你for下面是直接`cout << (*it + *(++it)) << " ";`，奇数的时候，最后那个数是`*it`，那你说现在的`*(++it)`是啥（这应该叫做越界还是未定义行为呢？），所以在输出前可以加个if判断一下。

**Comment by naometh** [comment]
谢谢，我自己在试试。
