### ISSUE TITLE
关于右值引用的问题

### ISSUE THREAD

**Issue by Nwpuer** [ReadingLab/Discussion-for-Cpp#56]
在C++ Primer第13章中，有这样一个函数：
`void StrVec::push_back(string &&s)
{chk_n_alloc();
alloc.construct(first_free++,std::move(s));`
我有这样的疑惑：为什么s本身已经是右值了，还需要用move函数呢？
后来看到第15章时，看到一个类似的函数，它是这样解释的：尽管s的类型是右值引用类型，但实际上s本身（和任何其他变量一样）是个左值。
这让我不能理解，为什么s是个右值引用类型的同时还能是左值呢？引用类型难道不仅仅是一个别名吗？

**Comment by pezy** [comment]
> 为什么s本身已经是右值了，还需要用move函数呢？

右值是无名的，s 显然是左值。

> 为什么s是个右值引用类型的同时还能是左值呢？

右值引用本来就可以是左值，也可以是右值的。

> 引用类型难道不仅仅是一个别名吗？

引用的确就是一个别名，但可以是另一个名字（譬如我们的网络 ID），但也可以是匿名（譬如知乎上的匿名回答）。那么作为 ID 的时候，就是左值；而作为匿名的时候，便是右值。

**Comment by Nwpuer** [comment]
明白了，我把右值引用和右值搞混了。有名字的右值引用是左值。谢谢解惑！
