### ISSUE TITLE
14.43的答案是不是有问题呀

### ISSUE THREAD

**Issue by ZhangKKK** [ReadingLab/Discussion-for-Cpp#59]
要求是判断给定的int值能否被int容器中的所有元素整除,然而any_of只要有一个符合不就返回为真了吗..
是不是应该改成all_of呀?
还有一个问题,
auto predicator = [&](int i){ return 0 == mod(input, i); };
这里的[&]是什么意思呀,好像效果和[input,mod]一样呢...

**Comment by pezy** [comment]
这个是中英文版本差别造成的，应该算是中文版翻译过程中的 Bug。

详细情况请见 @Mooophy 在 Mooophy/Cpp-Primer#251 中论述。

**Comment by pezy** [comment]
> 这里的[&]是什么意思呀,好像效果和[input,mod]一样呢...

建议你再复习一下 [Lambda](http://zh.cppreference.com/w/cpp/language/lambda) 表达式相关知识。

`[&]` 代表 **按引用捕获在lambda表达式所在函数的函数体中提及的全部自动储存持续性变量**

**Comment by ZhangKKK** [comment]
谢谢你这么耐心哈,我的确是看得太快了 看到后面前面都快忘光了...

**Comment by Mooophy** [comment]
@ZhangKKK 

lambda表达式和变量捕捉的概念很有用，特别是我们接触其他语言的时候。C++的好处之一是程序员的控制精度。在很多语言里捕捉方式是唯一的,而在C++里程序员可以自行指定捕捉的方式。此处的[&]代表以引用的方式进行捕捉，这是很多其他语言的唯一的捕捉方式，比如C#。
