### ISSUE TITLE
Mu's fantasy

### ISSUE THREAD

**Issue by Mooophy** [ReadingLab/Discussion-for-Cpp#6]
@mudongliang Mooophy/Cpp-Primer#215
 你到底想干嘛？

**Comment by mudongliang** [comment]
I don't want to do anything but to discuss about the pull request !

**Comment by Mooophy** [comment]
可#215里面啥修改都没有啊。

**Comment by mudongliang** [comment]
你稍等一下，我明明和pezy还讨论过呢，怎么可能没有呢？？
![screenshot from 2015-04-20 15 49 46](https://cloud.githubusercontent.com/assets/6214861/7225817/ec053f82-e774-11e4-8926-84d36b01c197.png)

**Comment by mudongliang** [comment]
我修改了ex3_16.cpp 写了一个函数版本和一个template版本

**Comment by mudongliang** [comment]
https://github.com/mudongliang/Cpp-Primer/commit/10f0fa843c338d4392c11ea3ab39e0bf33e865db
这是我推送的修改！

**Comment by Mooophy** [comment]
嗯。。不知哪出问题了，我这边儿看到的PR没有任何修改。

我看了你的函数版本和泛型版本，质量还是不错的。我和 @pezy 商量了一下，决定还是不要在第三章出现重载和泛型之类等中高级语法，避免给新手造成困扰。

如果感兴趣的话，可以到ch14重载、ch16泛型查查bug什么的。能理解你参与的热情，但希望能把自己的能力发挥到刀刃上。

**Comment by mudongliang** [comment]
我也发现了一个问题，我当时是用了两个分支，master和developer。现在发现developer分支中的那一次commit已经莫名奇妙消失了！如果你们两个认为这样的话，那这个PR就算了
不过Mooophy你注意一下ex3_21.他里面就有模板的版本，而且我还在README中发现了一个bug！

**Comment by pezy** [comment]
@mudongliang 嗯，那你能否单独针对 README 里的链接错误发一个 RP？

**Comment by mudongliang** [comment]
@pezy 好的，马上。

**Comment by Mooophy** [comment]
@mudongliang ex3_21那个泛型版本从很早就有了，一直也没删。现在关注的人多了，就不太建议这种玩票式的代码了，否则repo很难维护和管理。

**Comment by mudongliang** [comment]
@Mooophy 好的，说实话我就是在ex3_21的启发下，才取写ex3_16的。关于Cpp我也是新手，我当时还是临时学了一下模板，才做的PR。所以我建议你把这个文件删除！

**Comment by Mooophy** [comment]
嗯，回头你发个Issue，建议一下删除目前的泛型版本。
然后我们择机删除一下即可。

**Comment by mudongliang** [comment]
行，不过我想问你一下刚才的那个问题会不会是github的bug啊？
