### ISSUE TITLE
练习13.12的疑惑

### ISSUE THREAD

**Issue by gaolexx** [ReadingLab/Discussion-for-Cpp#60]
How many destructor calls occur in the following code fragment?

```
bool fcn(const Sales_data *trans, Sales_data accum)
{
    Sales_data item1(*trans), item2(accum);
    return item1.isbn() != item2.isbn();
}
```

为什么答案是`3 times. There are accum, item1 and item2.`

我不明白trans为什么不折构，求解，谢谢

**Comment by pezy** [comment]
> 我不明白trans为什么不折构，求解，谢谢

你先说说为什么 trans 会被析构？

**Comment by gaolexx** [comment]
我初学，猜测是因为它是引用所以不折构，对么？？花了好久也找不到书里面有说，所以问问

**Comment by pezy** [comment]
> 是因为它是引用所以不折构

它分明是个指针啊。我严重怀疑你前面的章节有没有细看。

析构是针对对象来说的，会在超出对象作用域的时候发生。那么对于 trans 指针来说，它所指向的对象， 显然在这个函数作用域范围**之外**。那么函数结束的时候，是完全不会影响到那个对象的。

**Comment by gaolexx** [comment]
我的意思是指针，码错了，老师规定我们每周三四章的往下看，所以看的囫囵吞枣了，听你这么一说，开始懂了，😏
