### ISSUE TITLE
5.3节 switch内部的变量定义

### ISSUE THREAD

**Issue by SlothSimon** [ReadingLab/Discussion-for-Cpp#66]
这一块给了一个例子，对于其中的一个注释不太理解。

```
case true:
    string file_name;    //  错误：控制流绕过一个隐式初始化的变量
    int ival = 0;
    int jval;    //  正确：因为jval没有初始化
    break;
case false:
    jval = next_num();
    if (file_name.empty())
        // ...
```

为什么file_name会隐式初始化而jval不会？是因为string不是内置类型吗？所有的非内置类型都会隐式初始化？
另外，int类型没有初始化而输出时其实会输出0，那这个int类型到底有没有初始化呢？（用的mac上的g++，不知道是不是有影响）
谢谢！

**Comment by pezy** [comment]
建议你重新复习一下 3.2 节的 Default Initialization 这一小节.

> 为什么file_name会隐式初始化而jval不会？

因为 file_name 是 `std::string` 类型, 而 `jval` 是 `int`.

> 是因为string不是内置类型吗？

这样说不准确, 首先, `string` 是一个 class type. 一个 class type 是否可以隐式初始化, 完全取决于该类的设计(这个14, 15 章会细讲). 但可以肯定的是, `std::string` 允许隐式初始化.

> 所有的非内置类型都会隐式初始化？

显然不是. 你可以轻松定义一个类型, 而不提供隐式初始化.

> int类型没有初始化而输出时其实会输出0，那这个int类型到底有没有初始化呢？

如果你指的是 `jval`, 那么它的值是未定义的. 可能是任何值, mac 上偏向于是 0, windows 上就不好说了.

**Comment by SlothSimon** [comment]
重读这一节＋查资料后，对于值初始化和默认初始化又有点想法，看书上的介绍（7.5.3节）感觉值初始化算是默认初始化的一种，但是对于二者的区别还不甚了了。
另外，除了函数体内内置类型的默认初始化后值是未定义外，还有别的情况会导致定义的变量值未定义吗？
非常感谢！

**Comment by pezy** [comment]
> 还有别的情况会导致定义的变量值未定义吗

有, 譬如类的某些成员变量.

``` cpp
class c {
    int i; // 值未定义
};
```
