### ISSUE TITLE
Question about Cpp-Prime/ch03/ex3_20 

### ISSUE THREAD

**Issue by mudongliang** [ReadingLab/Discussion-for-Cpp#7]
@Mooophy
[ex3_20.cpp] (https://github.com/Mooophy/Cpp-Primer/blob/master/ch03/ex3_20.cpp) has a confused logic. This version of file lost in readability and logic!
So I suggest we separate it into [a] (https://github.com/mudongliang/Cpp-Primer/blob/master/ch03/ex3_20a.cpp) and [b] (https://github.com/mudongliang/Cpp-Primer/blob/master/ch03/ex3_20b.cpp) , and one answer per question!
This will have a clear logic and readability!

**Comment by Mooophy** [comment]
听下原作者的意见 @pezy

**Comment by Mooophy** [comment]
我鼓励用英语，但建议行文更认真一些。你的英文表达里面有很多cet4级别的错误，比如：
这里应该用confusing而不是confused。

**Comment by pezy** [comment]
> Exercise 3.20: 
> Read a set of integers into a vector. **Print the sum of each pair of adjacent elements**. Change your program so that it **prints the sum of the first and last elements, followed by the sum of the second and second-to- last, and so on**.

I am confused about what was going on... Why did it have to be divided into two parts? :confused:

**Comment by mudongliang** [comment]
还是写中文吧。
我的意见是这样的。我并不是非要把这个文件分成两个，只是因为两个混在一起，逻辑上有些不是很好，可读性也不是很好！如果是我的话，我肯定不会写这种风格的代码的！
如果可以两个问题放在一个文件中，而且逻辑很清晰的话，那最好！

2015-04-20 21:12 GMT+08:00 pezy <notifications@github.com>:

**Comment by pezy** [comment]
> 逻辑上有些不是很好，可读性也不是很好

可否详细说明？

**Comment by mudongliang** [comment]
![screenshot from 2015-04-20 21 29 23](https://cloud.githubusercontent.com/assets/6214861/7230923/5db68148-e7a4-11e4-8d8a-03d6f667f4af.png)
我觉得，这个if...else if...else...有点问题！
本来的结构十分清晰，对于相邻的加法，如果size == 0 / 1 ，是无法执行的;
对于首未的加法，如果size == 0 ， 程序无法执行。
这样一写，反而需要仔细看一下。
这是我的第一感觉，如果你觉得我的想法幼稚，请忽略这个issue，也不用回复了！
因为本身这个文件的功能就很简单！

**Comment by pezy** [comment]
@mudongliang 有道理，你能否仅针对这道题再发一个 RP，麻烦了。
