### ISSUE TITLE
vs2013 不支持 (*it).empty(); 或 it->empty(); ?

### ISSUE THREAD

**Issue by PeteHenry** [ReadingLab/Discussion-for-Cpp#8]
```cpp
	string str(4, 'c');
	for (auto it = str.begin(); it != str.end(); ++it)
		if ((*it).empty())
			cout << *it << endl;
```
今天复习 string 时，想到的后面的迭代器，用了下结果有错误，想知道是我写错了？

**Comment by pezy** [comment]
`*it` 是 `char`. 没有 `empty` 方法.

**Comment by PeteHenry** [comment]
@pezy 恩
但
```cpp
	vector<int> ver(4, 'c');
	for (auto it = ver.begin(); it != ver.end() && it->empty(); ++it){

	}
```
中的 it->empty() 也显示有错误。

**Comment by PeteHenry** [comment]
额对了，vector 中的也是 char , 3Q

**Comment by PeteHenry** [comment]
@pezy 上面的问题也不严谨 vector<int> ver(4,'c');   // int 哈
再问下问题：
```cpp
#include <iostream>
#include <string>
using std::string;
using std::cin;
using std::cout; using std::endl;

int main(){
	string line;
	while (getline(cin, line))
		if (!line.empty())
			cout << line << endl;
	//while (getline(cin, line)){
	//	if (!line.empty())
	//		cout << line << endl;
	//}
	return 0;
}
```
输入一段话：
For the past three years, art director Matilda Kahl has been wearing the same outfit to work every single day.

“ I just wanted to save some time and energy,” she explained to Business Insider.
发现结果是不一样的，没 {} 的只能读 1 行，然后输出？

**Comment by pezy** [comment]
@PeteHenry 没明白你的问题。

这里要不要 {} 效果是一样的。都是：输入一行，回车，输出；输入一行，回车，输出。输入 EOF，退出。

**Comment by PeteHenry** [comment]
我感觉是一样的，所以结果使我有点迷茫
当 ···while{}··· 时，输出：
···
For the past three years, art director Matilda Kahl has been wearing the same ou
tfit to work every single day.
For the past three years, art director Matilda Kahl has been wearing the same ou
tfit to work every single day.

“ I just wanted to save some time and energy,” she explained to Business Insid
er.
“ I just wanted to save some time and energy,” she explained to Business Insid
er.
^Z
···
当 ···while··· 没用 {} 时，输出：
···
For the past three years, art director Matilda Kahl has been wearing the same ou
tfit to work every single day.
For the past three years, art director Matilda Kahl has been wearing the same ou
tfit to work every single day.
···
都不用 ctr+z 的结束符
当时感觉···while···这样···for···呢，才有了上面的测试

**Comment by pezy** [comment]
@PeteHenry 确认一下，你的第二种输出（不用 Ctrl+Z 结束的）对应的代码是上面贴的那个吗？

我这边跑你贴的代码，是和第一种输出完全一样的。

**Comment by PeteHenry** [comment]
@pezy
不能截图有点烦，我直接右键粘贴的，输入的是一样的
手动输入也是只要按下 ```Enter``` 键就，直接到达 ```return 0;``` 语句那

**Comment by pezy** [comment]
@PeteHenry 可以用 QQ 截图，然后在下面输入对话框直接 Ctrl+v

也可以点：
![image](https://cloud.githubusercontent.com/assets/1147451/7266291/0906313e-e8da-11e4-9c2c-d00e7059690a.png)
手动上传。

**Comment by pezy** [comment]
@PeteHenry  如果代码就是：

```cpp
int main()
{
	string line;
	while ( getline(std::cin, line) )
		if (!line.empty())
			cout << line << endl;
}
```

我敢肯定必须按 `Ctrl` + `Z` 才可以退出，可以让 @Mooophy 也试试。

**Comment by PeteHenry** [comment]
@pezy 
查出问题的，我在 ```return 0;``` 那设置的断点，输入一行后，点下继续才能继续输入，所以这样 ```Ctrl + Z``` 也是必要的了
因为以前没用过 vs，使用经验不够，不知道为什么会走到断点那（怎么会走到 ```return 0; ```）

**Comment by pezy** [comment]
@PeteHenry  :ok_hand:

**Comment by PeteHenry** [comment]
@pezy 
3Q，走到 ```return 0;```
这函数不是结束了么，所以走到了 ```return 0;``` 点继续还能输入 感觉有点
谢谢了

**Comment by PeteHenry** [comment]
又测试了下
```
#include <iostream>
#include <string>
using std::string;
using std::cin;
using std::cout; using std::endl;

int main(){
	string line;
	while (getline(cin, line))
		if (!line.empty())
			cout << line << endl;
	cout << 1 << endl;
	int a = 0;
}
```
在 ```cout << 1 << endl;``` 那设置断点，同样会触发断点，但不会执行
加了 {} 的 ```while{}``` ，不会在 ``` while``` 运行结束前，触发断点
@pezy 
谢谢，现在感觉好多了

**Comment by pezy** [comment]
> 不知道为什么会走到断点那（怎么会走到 return 0;）

> 这函数不是结束了么，所以走到了 return 0; 点继续还能输入 感觉有点

抱歉，刚才我以为你明白了。。

这样的现象是 VS 调试模式的一个惯例。（这也是为什么微软代码规范里强调大括号一定要有，且一定要单独一行的原因）

具体来看，你在 `return 0;` 那里设置了一个断点，那么当输入完一句话时，处于什么状态呢？

1. 本次循环已经结束
2. 还没进入下一次循环

如果你写了大括号，那么输出那句话之后，程序会先经过 `}`，再进入下一次循环。

但你现在把 {} 去掉了，VS 就会将那个状态合并到下一句（即 `return 0;` 上），所以当程序需要经过 `}` 的时候，就停到了下一句（`return 0;`）上。以至于你走不到 2 的阶段。

这么说你是否明白了呢？

**Comment by PeteHenry** [comment]
@pezy 
用 ```cout << 1 << endl;``` 调试完就差不多知道 microsoft 的 ```while``` 调试原理
你对于 ```}``` 的解释，更好的诠释的 ```while{}``` 在有和没 {} 时，运行的机制
引用”刚才我以为你明白了“，显示出果然 @pezy 站的高啊
呵呵 谢谢前辈，while 这问题应该差不多了

**Comment by PeteHenry** [comment]
http://zh-google-styleguide.readthedocs.org/en/latest/google-cpp-styleguide/contents/
找了份 c++ 的编码规范
@pezy 谢谢，可以结案了

**Comment by pezy** [comment]
@PeteHenry  如果平时都用 VS 的话，尽量参考：[微软的代码风格](https://1code.codeplex.com/releases/view/84683)。

**Comment by PeteHenry** [comment]
@pezy 
Thanks,I should improve my English.
